---
- hosts: 172.31.15.102
  become: true
  tasks:
    - ping:
    - name: moving war file from target to tomcat webapps folder
      copy:
        src: target/maven-web-applications.war
        dest: /opt/apache-tomcat-9.0.65/webapps/
...
